// Generated by gencpp from file can_msgs/Kd_Can_Frame_Start.msg
// DO NOT EDIT!


#ifndef CAN_MSGS_MESSAGE_KD_CAN_FRAME_START_H
#define CAN_MSGS_MESSAGE_KD_CAN_FRAME_START_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace can_msgs
{
template <class ContainerAllocator>
struct Kd_Can_Frame_Start_
{
  typedef Kd_Can_Frame_Start_<ContainerAllocator> Type;

  Kd_Can_Frame_Start_()
    : header()
    , stx(0)
    , len(0)
    , seq(0)
    , sys(0)
    , comp(0)
    , cmd(0)  {
    }
  Kd_Can_Frame_Start_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , stx(0)
    , len(0)
    , seq(0)
    , sys(0)
    , comp(0)
    , cmd(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _stx_type;
  _stx_type stx;

   typedef uint8_t _len_type;
  _len_type len;

   typedef uint8_t _seq_type;
  _seq_type seq;

   typedef uint8_t _sys_type;
  _sys_type sys;

   typedef uint8_t _comp_type;
  _comp_type comp;

   typedef uint8_t _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> const> ConstPtr;

}; // struct Kd_Can_Frame_Start_

typedef ::can_msgs::Kd_Can_Frame_Start_<std::allocator<void> > Kd_Can_Frame_Start;

typedef boost::shared_ptr< ::can_msgs::Kd_Can_Frame_Start > Kd_Can_Frame_StartPtr;
typedef boost::shared_ptr< ::can_msgs::Kd_Can_Frame_Start const> Kd_Can_Frame_StartConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'can_msgs': ['/home/nvidia/kd_px4_can/src/ros_canopen/can_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ed2d8fa2509a0e1b936f41c90c897b9";
  }

  static const char* value(const ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ed2d8fa2509a0e1ULL;
  static const uint64_t static_value2 = 0xb936f41c90c897b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_msgs/Kd_Can_Frame_Start";
  }

  static const char* value(const ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 stx\n\
uint8 len\n\
uint8 seq\n\
uint8 sys\n\
uint8 comp\n\
uint8 cmd\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.stx);
      stream.next(m.len);
      stream.next(m.seq);
      stream.next(m.sys);
      stream.next(m.comp);
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Kd_Can_Frame_Start_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_msgs::Kd_Can_Frame_Start_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "stx: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stx);
    s << indent << "len: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.len);
    s << indent << "seq: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.seq);
    s << indent << "sys: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sys);
    s << indent << "comp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.comp);
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MSGS_MESSAGE_KD_CAN_FRAME_START_H
