// Generated by gencpp from file can_msgs/Kd_Can_Frame_End.msg
// DO NOT EDIT!


#ifndef CAN_MSGS_MESSAGE_KD_CAN_FRAME_END_H
#define CAN_MSGS_MESSAGE_KD_CAN_FRAME_END_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace can_msgs
{
template <class ContainerAllocator>
struct Kd_Can_Frame_End_
{
  typedef Kd_Can_Frame_End_<ContainerAllocator> Type;

  Kd_Can_Frame_End_()
    : header()
    , crca(0)
    , crcb(0)  {
    }
  Kd_Can_Frame_End_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , crca(0)
    , crcb(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _crca_type;
  _crca_type crca;

   typedef uint8_t _crcb_type;
  _crcb_type crcb;





  typedef boost::shared_ptr< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> const> ConstPtr;

}; // struct Kd_Can_Frame_End_

typedef ::can_msgs::Kd_Can_Frame_End_<std::allocator<void> > Kd_Can_Frame_End;

typedef boost::shared_ptr< ::can_msgs::Kd_Can_Frame_End > Kd_Can_Frame_EndPtr;
typedef boost::shared_ptr< ::can_msgs::Kd_Can_Frame_End const> Kd_Can_Frame_EndConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'can_msgs': ['/home/nvidia/kd_px4_can/src/ros_canopen/can_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> >
{
  static const char* value()
  {
    return "916ba27749b7ac9e7211be94f6664329";
  }

  static const char* value(const ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x916ba27749b7ac9eULL;
  static const uint64_t static_value2 = 0x7211be94f6664329ULL;
};

template<class ContainerAllocator>
struct DataType< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_msgs/Kd_Can_Frame_End";
  }

  static const char* value(const ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 crca\n\
uint8 crcb\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.crca);
      stream.next(m.crcb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Kd_Can_Frame_End_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_msgs::Kd_Can_Frame_End_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "crca: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.crca);
    s << indent << "crcb: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.crcb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MSGS_MESSAGE_KD_CAN_FRAME_END_H
